version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: gem install bundler
      - run: gem install middleman
      - run: bundle install
      - deploy:
          command: bundle exec middleman deploy
