version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: gem install execjs
      - deploy:
          command: bundle exec middleman deploy
