version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: 
        - command: |
            git config user.email $GIT_USER_EMAIL
            git config user.name $GIT_USER_NAME
      - deploy:
          command: bundle exec middleman deploy
