version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: git config user.email $GIT_USER_EMAIL
      - run: git config user.name $GIT_USER_NAME
      - deploy:
          command:
            - bundle exec middleman deploy
