version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run: pip install -r requirements/dev.txt
      - deploy:
        branch: master
        commands:
          - git config user.email $GIT_USER_EMAIL
          - git config user.name $GIT_USER_NAME
          - bundle exec middleman deploy
